POST http://localhost:3003/api/login
Content-Type: application/json

{
    "name": "some1",  
  "username": "user456",
  "password": "secretpass123"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXI0NTYiLCJpZCI6IjY3OGMxMjczNTZhNjY0NTIxNGQ2YjBhNiIsImlhdCI6MTczNzMwNTM2NX0.bAa7Uhu2U-RI90fW5IwzTliFvfQy4_i85EeMT6eQ3xY

{ 
  "title": "Test blog 2",
  "author": "Mr. Test",
  "url": "/test/url",
  "likes": 5
}