POST http://localhost:3003/api/login
Content-Type: application/json

{
    "name": "some1",  
  "username": "user2",
  "password": "pass123"
}

###
GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs/6882a224a57205b3cbbeaccc/comments
Content-Type: application/json
Authorization: Bearer 

{ 
  "text": "first comment"
}